[package]
name = "triklops"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.0", features = ["derive"] }
image = "0.24.6"
imageproc = "0.23.0"
rand = "0.8.5"
svg = "0.18.0"
indicatif = "0.16.2"
rayon = "1.10.0"