[package]
name = "triklops"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = { version = "0.31.1", features = ["image"] }
image = "0.25.6"
imageproc = "0.25.0"
rand = "0.8"
rayon = "1.10.0"
svg = "0.18.0"
rfd = "0.15.3"
env_logger = "0.11.8"
